// here we define our constants

const ADD_COUNT = 'ADD_COUNT';
const SUBMIT_SIGNUP_FORM = 'SUBMIT_SIGNUP_FORM';
const LOGIN_INPUT = 'LOGIN_INPUT';
const VALID_LOGIN = 'VALID_LOGIN';
const SIGNUP_FORM_INPUT = 'SIGNUP_FORM_INPUT';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const NEW_PLANS = 'NEW_PLANS';
const NEW_LOCATION_INPUT = 'NEW_LOCATION_INPUT';
const LOGIN_KEYDOWN = 'LOGIN_KEYDOWN';
const ACTIVITY_FORM_INPUT = 'ACTIVITY_FORM_INPUT';
const SUBMIT_ACTIVITY_FORM = 'SUBMIT_ACTIVITY_FORM';
const ADD_ACTIVITIES = 'ADD_ACTIVITIES';

export {
  ADD_COUNT,
  SUBMIT_SIGNUP_FORM,
  LOGIN_INPUT,
  VALID_LOGIN,
  SIGNUP_FORM_INPUT,
  GET_ACTIVITIES,
  NEW_PLANS,
  NEW_LOCATION_INPUT,
  LOGIN_KEYDOWN,
  ACTIVITY_FORM_INPUT,
  SUBMIT_ACTIVITY_FORM,
  ADD_ACTIVITIES,
};
